### ISSUE TITLE
recommend we pin this repository

### ISSUE THREAD

**Issue by erikerlandson** [Enterprise-Neurosystem/governance#2]
github allows us to pin repositories, so they show up at the top of the organization home page.  I do not seem to have privileges to do this for EN github org, but the governance repo should be pinned so it is always prominent for anyone visiting this org

**Comment by duck-rh** [comment]
Quack,

I can see you in the list of admin of this org. Maybe that was fixed in the meantime. I pinned the repo.

\\_o<
